#!/bin/bash
# This hook is run after every virtualenv is activated.

function export_env() {
    # Export every envvar in .env if it's not commented out.
    # If the variable already exists, keep a backup so we can switch back wehn deactivating.
    while read line; do
      if [[ $line != \#* && $line == *\=* ]] 
      then
        IFS='=' read -ra keyvalue <<< "$line"
        # echo "key: " ${keyvalue[0]} ", value: " ${keyvalue[1]}
        if [[ -n ${!keyvalue[0]} ]]
        then
            export ${keyvalue[0]}_BACKUP=${!keyvalue[0]}
        fi
        export $line
      fi
    done <$1
    unset line
    unset keyvalue
}

function get_dotenv_path {
    if [ -f "$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME" ]
    then
        typeset project_dir="$(cat "$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME")"
        if [ ! -z "$project_dir" ]
        then
            echo $project_dir/.env
        else
            echo "Project directory $project_dir does not exist" 1>&2
            exit 1
        fi
    else
        echo "No project set in $VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME" 1>&2
        exit 1
    fi   
}

export_env $(get_dotenv_path)